from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"

if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.config import get_settings
from app.services.fixture_ingestion_service import FixtureIngestionService


CACHE_DIR = ROOT / "data" / "cache"
REPORT_DIR = ROOT / "report"

CACHE_PATH = CACHE_DIR / "fixtures_latest.json"
REPORT_PATH = REPORT_DIR / "fixture_cache_report.json"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def existing_cache_summary() -> dict[str, Any]:
    if not CACHE_PATH.exists():
        return {
            "exists": False,
            "path": str(CACHE_PATH.relative_to(ROOT)),
            "fixture_count": 0,
            "generated_at": None,
        }

    try:
        payload = json.loads(CACHE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {
            "exists": True,
            "path": str(CACHE_PATH.relative_to(ROOT)),
            "fixture_count": 0,
            "generated_at": None,
            "error": f"cache_read_error: {exc}",
        }

    fixtures = payload.get("fixtures", []) if isinstance(payload, dict) else []
    return {
        "exists": True,
        "path": str(CACHE_PATH.relative_to(ROOT)),
        "fixture_count": len(fixtures) if isinstance(fixtures, list) else 0,
        "generated_at": payload.get("generated_at") if isinstance(payload, dict) else None,
    }


def build_failure_report(error: str, started_at: str) -> dict[str, Any]:
    return {
        "ok": False,
        "generated_at": utc_now(),
        "started_at": started_at,
        "cache_path": str(CACHE_PATH.relative_to(ROOT)),
        "report_path": str(REPORT_PATH.relative_to(ROOT)),
        "fixture_count": 0,
        "cache_written": False,
        "error": error,
        "previous_cache": existing_cache_summary(),
        "usage_note": (
            "Fixture cache sync failed, but the previous cache was preserved. "
            "The FastAPI /fixtures?source=auto route will use the existing cache if available, "
            "otherwise it will fall back to demo fixtures."
        ),
    }


def sync_fixture_cache(timeout_seconds: int, allow_empty: bool) -> dict[str, Any]:
    started_at = utc_now()
    settings = get_settings()
    service = FixtureIngestionService(settings, timeout_seconds=timeout_seconds)

    try:
        payload = service.ingest()
    except Exception as exc:  # noqa: BLE001 - script must report failures instead of crashing
        report = build_failure_report(f"ingestion_exception: {exc}", started_at)
        write_json(REPORT_PATH, report)
        return report

    fixtures = payload.get("fixtures", [])
    if not isinstance(fixtures, list):
        report = build_failure_report("invalid_ingestion_payload: fixtures is not a list", started_at)
        report["raw_payload_type"] = type(payload).__name__
        write_json(REPORT_PATH, report)
        return report

    fixture_count = len(fixtures)
    source_summaries = payload.get("sources", [])
    if not isinstance(source_summaries, list):
        source_summaries = []

    cache_payload = {
        "generated_at": payload.get("generated_at") or utc_now(),
        "synced_at": utc_now(),
        "fixture_count": fixture_count,
        "sources": source_summaries,
        "fixtures": fixtures,
        "usage_note": (
            "This cache is generated by scripts/sync_fixture_cache.py. "
            "FastAPI /fixtures?source=auto reads this file before falling back to demo fixtures. "
            "No live betting or real-money betting actions are performed."
        ),
    }

    should_write_cache = fixture_count > 0 or allow_empty

    report = {
        "ok": fixture_count > 0 or allow_empty,
        "generated_at": utc_now(),
        "started_at": started_at,
        "cache_path": str(CACHE_PATH.relative_to(ROOT)),
        "report_path": str(REPORT_PATH.relative_to(ROOT)),
        "fixture_count": fixture_count,
        "cache_written": should_write_cache,
        "allow_empty": allow_empty,
        "previous_cache": existing_cache_summary(),
        "sources": source_summaries,
        "usage_note": (
            "If fixture_count is 0 and allow_empty is false, the previous fixture cache is preserved."
        ),
    }

    if should_write_cache:
        write_json(CACHE_PATH, cache_payload)
    else:
        report["ok"] = False
        report["error"] = "empty_ingestion_result: cache not overwritten"

    write_json(REPORT_PATH, report)
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync normalized World Cup fixtures into the local cache used by FastAPI."
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=12,
        help="Timeout per external source request. Default: 12.",
    )
    parser.add_argument(
        "--allow-empty",
        action="store_true",
        help="Allow overwriting the fixture cache even when ingestion returns 0 fixtures.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report = sync_fixture_cache(
        timeout_seconds=args.timeout_seconds,
        allow_empty=args.allow_empty,
    )

    print(json.dumps(report, indent=2, ensure_ascii=False))

    # Do not fail CI just because external fixture providers are unavailable.
    # The JSON report is the source of truth for whether cache was refreshed.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
